### ISSUE TITLE
Execution context was destroyed, most likely because of a navigation

### ISSUE THREAD

**Issue by tonxxd** [tungs/timesnap#27]
Hello, I am getting this error when trying to record a webgl canvas in a react webpage.

```
Error: Execution context was destroyed, most likely because of a navigation. 
    at rewriteError (/node_modules/puppeteer/lib/ExecutionContext.js:167:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext._evaluateInternal (/node_modules/puppeteer/lib/ExecutionContext.js:120:56)
    at async ExecutionContext.evaluate (/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async Promise.all (index 2)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (/node_modules/puppeteer/lib/helper.js:111:15)
    at /node_modules/timesnap/lib/overwrite-time.js:222:18
    at Array.map (<anonymous>)
    at Object.goToTimeAndAnimate (/node_modules/timesnap/lib/overwrite-time.js:221:36)
    at /node_modules/timesnap/index.js:231:29
    at loop (/node_modules/timesnap/lib/utils.js:40:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

But i don't know if it could be an issue related to the wrong setup of the script, dom not loaded in time o or something else. 
Can Someone please help me solve this issue?
Thanks

**Comment by tungs** [comment]
Hey there, could you post what page you're trying to capture as well as what command options you're using to do it? From what I've seen, this issue can stem from using immediate capture mode on a webgl rendered canvas, though there may be other cases too.

**Comment by tungs** [comment]
In the case of using canvas capture mode on a webgl rendered canvas, you can instead use the immediate canvas mode, [as seen here](https://github.com/tungs/timesnap#cli-options-canvas-capture-mode)
